pool: "dbr-vmss-test"
trigger:
  - dbr-containerjob-test

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
- bash: for i in {1..120}; do echo "count:"" $i" && sleep 1s; done
  displayName: wait 2 min.
  target: "ubuntu:latest"